'use client';
import React from "react"
import Link from "next/link"
import PolicyLayout from "@/app/components/PolicyLayout";
import { CONTACT_INFO } from "@/app/constants";


const PrivacyPolicy = () => {
    return (
        <PolicyLayout title="Privacy Policy" lastUpdated="January 5th 2026">
            <section>
                <p>
                    This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                </p>
                <p>
                    We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                </p>
            </section>

            <section>
                <h2>Interpretation and Definitions</h2>
                <h3>Interpretation</h3>
                <p>
                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                </p>

                <h3>Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-2">
                    <li>
                        <strong>Account</strong> means a unique account created for You to access our Service or parts of our
                        Service.
                    </li>
                    <li>
                        <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
                    </li>
                    <li>
                        <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
                        refers to Fit Choice World
                    </li>
                    <li>
                        <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other
                        device by a website, containing the details of Your browsing history on that website among its many
                        uses.
                    </li>
                    <li>
                        <strong>Country</strong> refers to: Karnataka, India
                    </li>
                    <li>
                        <strong>Device</strong> means any device that can access the Service such as a computer, a cell phone
                        or a digital tablet.
                    </li>
                    <li>
                        <strong>Personal Data</strong> is any information that relates to an identified or identifiable
                        individual.
                    </li>
                    <li>
                        <strong>Service</strong> refers to the Website.
                    </li>
                    <li>
                        <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf
                        of the Company. It refers to third-party companies or individuals employed by the Company to
                        facilitate the Service, to provide the Service on behalf of the Company, to perform services related
                        to the Service or to assist the Company in analyzing how the Service is used.
                    </li>
                    <li>
                        <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
                        Service or from the Service infrastructure itself (for example, the duration of a page visit).
                    </li>
                    <li>
                        <strong>Website</strong> refers to Fit Choice World, accessible from <Link className="underline text-orange-600 hover:text-orange-700 font-medium" href={"/"}>www.fitchoiceworld.com</Link>
                    </li>
                    <li>
                        <strong>You</strong> mean the individual accessing or using the Service, or the company, or other
                        legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                    </li>
                </ul>
            </section>

            <section>
                <h2>Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information
                    that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                </p>
                <ul className="list-disc pl-6 space-y-1">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                </ul>

                <h4>Usage Data</h4>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p>
                    Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
                    browser type, browser version, the pages of our Service that You visit, the time and date of Your visit,
                    the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p>
                    When You access the Service by or through a mobile device, We may collect certain information
                    automatically, including, but not limited to, the type of mobile device You use, Your mobile device
                    unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
                    Internet browser You use, unique device identifiers and other diagnostic data.
                </p>
                <p>
                    We may also collect information that Your browser sends whenever You visit our Service or when You
                    access the Service by or through a mobile device.
                </p>

                <h4>Tracking Technologies and Cookies</h4>
                <p>
                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
                </p>
                <ul className="list-disc pl-6 space-y-4">
                    <li>
                        <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                    </li>
                    <li>
                        <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
                    </li>
                </ul>
                <p>
                    Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
                </p>
                <p>
                    We use both Session and Persistent Cookies for the purposes set out below:
                </p>
                <ul className="space-y-6">
                    <li>
                        <strong className="block text-lg">Necessary / Essential Cookies</strong>
                        <p>
                            Type: Session Cookies <br></br>
                            Administered by: Us<br></br>
                            Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                        </p>
                    </li>
                    <li>
                        <strong className="block text-lg">Cookies Policy / Notice Acceptance Cookies</strong>
                        <p>
                            Type: Persistent Cookies <br></br>
                            Administered by: Us<br></br>
                            Purpose: These Cookies identify if users have accepted the use of cookies on the Website
                        </p>
                    </li>
                    <li>
                        <strong className="block text-lg">Functionality Cookies</strong>
                        <p>
                            Type: Persistent Cookies <br></br>
                            Administered by: Us<br></br>
                            Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.
                        </p>
                    </li>
                </ul>
                <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
                </p>
            </section>

            <section>
                <h2>Use of Your Personal Data</h2>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-4">
                    <li>
                        <strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.
                    </li>
                    <li>
                        <strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                    </li>
                    <li>
                        <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                    </li>
                    <li>
                        <strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications.
                    </li>
                    <li>
                        <strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.
                    </li>
                </ul>
            </section>

            <section>
                <h2>Retention of Your Personal Data</h2>
                <p>
                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p>
                    The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time.
                </p>
            </section>

            <section>
                <h2>Transfer of Your Personal Data</h2>
                <p>
                    Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
                </p>
                <p>
                    Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                </p>
            </section>

            <section>
                <h2>Security of Your Personal Data</h2>
                <p>
                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                </p>
            </section>

            <section>
                <h2>Changes to this Privacy Policy</h2>
                <p>
                    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                </p>
                <p>
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
            </section>

            <section>
                <h2>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                <ul className="list-disc pl-6 space-y-1">
                    <li>Email: {CONTACT_INFO.email}</li>
                    <li>Phone Number: {CONTACT_INFO.phone}</li>
                    <li>Address: {CONTACT_INFO.address}</li>
                </ul>
            </section>
        </PolicyLayout>
    );
};

export default PrivacyPolicy;
